name: GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Build and deploy
        run: |
          mkdir public
          cp -r * public/
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin main:gh-pages